-- Create the guestbook table
create table public.guestbook (
  id bigint generated by default as identity primary key,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
-- Note: Currently the simplified admin mode in the app doesn't rely on RLS policies for deletion (it uses the client secret),
-- but in a production environment with authenticated users, you would add policies here.

-- Example Policy: Allow anyone to read
alter table public.guestbook enable row level security;

create policy "Enable read access for all users"
on public.guestbook for select
using (true);

-- Example Policy: Allow anyone to insert (anon key)
create policy "Enable insert for all users"
on public.guestbook for insert
with check (true);

-- No delete policy is added here by default for "anon", meaning anonymous users cannot delete rows via Supabase API calls.
-- Deletion is handled by the app's secret code logic or a signed-in admin user in a full auth setup.
